### ISSUE TITLE
Support `prefix` option also with `TmpDirIfNecessary`?

### ISSUE THREAD

**Issue by rggjan** [Parquery/temppathlib#11]
Maybe `TmpDirIfNecessary` should also support the `prefix` option, to give a temporary directory a certain prefix (if no directory is provided already?

**Comment by mristin** [comment]
@rggjan thanks for the feature request! Could you please confirm that the latest code in the master works as you expected, and then I'll bump the minor version?

**Comment by rggjan** [comment]
Perfect, thanks a lot! :)

**Comment by mristin** [comment]
@rggjan The new version should be soon up.

Btw., if you haven't done so, please consider giving a star to the project to help its visibility.

**Comment by rggjan** [comment]
👍
