### ISSUE TITLE
Feature request: implement gettempdir()

### ISSUE THREAD

**Issue by bersbersbers** [Parquery/temppathlib#6]
See https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir

**Comment by mristin** [comment]
Hi @bersbersbers ,
Thank you very much for the feature request!

I created a pull request: #7 . Could you please check if it fits your use case and test it against your code?

**Comment by bersbersbers** [comment]
Works for me, thank :)

**Comment by mristin** [comment]
@bersbersbers I've just released 1.1.0 to PyPI.

Btw., if you haven't done so, could you please star the project to give it some visibility?
